<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="GisenCubeBase">
  <xacro:property name="pi" value="3.1415926535897931" />

  <xacro:property name="body_height" value="0.067" />
  <xacro:property name="wheel_x_dist" value="0.085" />
  <xacro:property name="wheel_y_dist" value="0.0825" />
  <xacro:property name="wheel_height" value="0.100" />
  <xacro:macro name="default_wheel_visual">
    <visual>
      <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_height / 2}" length="0.050" />
      </geometry>
      <material name="blue">
        <color rgba="0 0 0.8 1" />
      </material>
    </visual>
  </xacro:macro>
  <xacro:macro name="default_inertial" params="mass origin_xyz">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="${origin_xyz}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                                   izz="1.0" />
    </inertial>
  </xacro:macro>

  <link name="base_footprint" />
  <gazebo reference="base_footprint">
    <material>Gazebo/Red</material>
  </gazebo>
  <joint name="footprint_to_base" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link">base_link</child>
    <origin xyz="0 0 ${body_height}" rpy="0 0 0" />
  </joint>

  <link name="base_link" />
  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
  </gazebo>
  <joint name="base_to_box" type="fixed">
    <parent link="base_link" />
    <child link="box_link">box_link</child>
    <origin xyz="0 0 ${0.37 / 2}" rpy="0 0 0" />
  </joint>

  <link name="box_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.37 0.37 0.37" />
      </geometry>
      <material name="orange">
        <color rgba=".8 .2 0 1" />
      </material>
    </visual>
    <xacro:default_inertial mass="1.2" origin_xyz="0 0 0" />
  </link>
  <gazebo reference="box_link">
    <material>Gazebo/Orange</material>
  </gazebo>

  <joint name="wheel1_hinge" type="continuous">
    <parent link="base_link" />
    <child link="wheel1">wheel1</child>
    <origin xyz="${wheel_x_dist} ${wheel_y_dist} ${wheel_height / 2 - body_height}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="1" velocity="2.0" />
    <dynamics damping="0.3" friction="0.2" />
  </joint>
  <transmission name="trans1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel1_hinge">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanismReduction>64</mechanismReduction>
    </actuator>
  </transmission>

  <joint name="wheel2_hinge" type="continuous">
    <parent link="base_link" />
    <child link="wheel2">wheel2</child>
    <origin xyz="-${wheel_x_dist} ${wheel_y_dist} ${wheel_height / 2 - body_height}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="1" velocity="2.0" />
    <dynamics damping="0.3" friction="0.2" />
  </joint>
  <transmission name="trans2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel2_hinge">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanismReduction>64</mechanismReduction>
    </actuator>
  </transmission>

  <joint name="wheel3_hinge" type="continuous">
    <parent link="base_link" />
    <child link="wheel3">wheel3</child>
    <origin xyz="-${wheel_x_dist} -${wheel_y_dist} ${wheel_height / 2 - body_height}" rpy="0 0 0" />
    <axis xyz="0 -1 0" />
    <limit effort="1" velocity="2.0" />
    <dynamics damping="0.3" friction="0.2" />
  </joint>
  <transmission name="trans3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel3_hinge">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanismReduction>64</mechanismReduction>
    </actuator>
  </transmission>

  <joint name="wheel4_hinge" type="continuous">
    <parent link="base_link" />
    <child link="wheel4">wheel4</child>
    <origin xyz="${wheel_x_dist} -${wheel_y_dist} ${wheel_height / 2 - body_height}" rpy="0 0 0" />
    <axis xyz="0 -1 0" />
    <limit effort="1" velocity="2.0" />
    <dynamics damping="0.3" friction="0.2" />
  </joint>
  <transmission name="trans4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel4_hinge">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanismReduction>64</mechanismReduction>
    </actuator>
  </transmission>


  <link name="wheel1">
    <xacro:default_wheel_visual />

    <xacro:default_inertial mass="0.3085" origin_xyz="0 0 0" />
  </link>
  <gazebo reference="wheel1">
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="wheel2">
    <xacro:default_wheel_visual />

    <xacro:default_inertial mass="0.3085" origin_xyz="0 0 0" />
  </link>
  <gazebo reference="wheel2">
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="wheel3">
    <xacro:default_wheel_visual />

    <xacro:default_inertial mass="0.3085" origin_xyz="0 0 0" />
  </link>
  <gazebo reference="wheel3">
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="wheel4">
    <xacro:default_wheel_visual />

    <xacro:default_inertial mass="0.3085" origin_xyz="0 0 0" />
  </link>
  <gazebo reference="wheel4">
    <material>Gazebo/Blue</material>
  </gazebo>
<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace>/cube_base</robotNamespace>
  </plugin>
</gazebo>
</robot>

