wheel1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: wheel1
    joint_speed: 2.0
    motor:
        id: 3
        init: 0
        min: 0
        max: 4095

wheel2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: wheel2
    joint_speed: 2.0
    motor:
        id: 4
        init: 0
        min: 4095
        max: 0

wheel3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: wheel3
    joint_speed: 2.0
    motor:
        id: 1
        init: 0
        min: 0
        max: 4095

wheel4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: wheel4
    joint_speed: 2.0
    motor:
        id: 2
        init: 0
        min: 4095
        max: 0

